=== Pogas89/BeerXML/beers.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/beers"
    xmlns:tns="http://www.example.org/beers" elementFormDefault="qualified">
    <element name="beers">
        <complexType>
            <sequence>
                <element name="beer" maxOccurs="unbounded">
                    <complexType>
                        <sequence>
                            <element name="name" type="string"/>
                            <element name="type">
                                <simpleType>
                                    <restriction base="string">
                                        <enumeration value="dark"/>
                                        <enumeration value="ale"/>
                                        <enumeration value="lager"/>
                                        <enumeration value="alive"/>
                                    </restriction>
                                </simpleType>
                            </element>
                            <element name="alchoholType">
                                <simpleType>
                                    <restriction base="string">
                                        <enumeration value="alchohol"/>
                                        <enumeration value="nonalchohol"/>
                                    </restriction>
                                </simpleType>
                            </element>
                            <element name="manufactor" type="string"/>
                            <element name="ingridients">
                                <complexType>
                                    <sequence>
                                        <element name="water">
                                            <simpleType>
                                                <restriction base="int"/>
                                            </simpleType>
                                        </element>
                                        <element name="malt">
                                            <simpleType>
                                                <restriction base="int"/>
                                            </simpleType>
                                        </element>
                                        <element name="Hop">
                                            <simpleType>
                                                <restriction base="int"/>
                                            </simpleType>
                                        </element>
                                        <element name="sugar">
                                            <simpleType>
                                                <restriction base="int"/>
                                            </simpleType>
                                        </element>
                                    </sequence>
                                </complexType>
                            </element>
                            <element name="chars">
                                <complexType>
                                    <sequence>
                                        <element name="spiritAmount">
                                            <!--<complexType>
                                                <simpleContent>
                                                    <restriction base="double">
                                                        <attribute name="spiritAmount" use="optional"/>
                                                    </restriction>
                                                </simpleContent>
                                            </complexType>-->
                                            <simpleType>
                                                <restriction base="double"/>
                                            </simpleType>
                                        </element>
                                        <element name="transparency">
                                            <simpleType>
                                                <restriction base="int">
                                                    <minInclusive value="1"/>
                                                    <maxExclusive value="4"/>
                                                </restriction>
                                            </simpleType>
                                        </element>
                                        <element name="filtration">
                                            <simpleType>
                                                <restriction base="string">
                                                    <enumeration value="filtred"/>
                                                    <enumeration value="nonfiltred"/>
                                                </restriction>
                                            </simpleType>
                                        </element>
                                        <element name="nutritiveValue">
                                            <simpleType>
                                                <restriction base="int"/>
                                            </simpleType>
                                        </element>
                                        <element name="bottling">
                                            <simpleType>
                                                <restriction base="string">
                                                    <pattern value="([0-9]+)(\.)([0-9])+ [A-Za-z]+"/>
                                                </restriction>
                                            </simpleType>
                                        </element>
                                    </sequence>
                                </complexType>
                            </element>
                        </sequence>
                        <attribute name="id" use="required">
                            <simpleType>
                                <restriction base="ID">
                                    <pattern value="[a-zA-z0-9_]+"/>
                                </restriction>
                            </simpleType>
                        </attribute>
                    </complexType>
                </element>
            </sequence>
        </complexType>
    </element>
</schema>

=== Pogas89/BeerXML/beers.xml
<?xml version="1.0" encoding="UTF-8" ?>
<beers xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://www.example.org/beers" xsi:schemaLocation="http://www.example.org/vauchers beers.xsd">
    <beer id="beer1">
        <name>Warka</name>
        <type>dark</type>
        <alchoholType>alchohol</alchoholType>
        <manufactor>Polska Beers Inc.</manufactor>
        <ingridients>
            <water>70</water>
            <malt>10</malt>
            <Hop>15</Hop>
            <sugar>5</sugar>
        </ingridients>
        <chars>
            <spiritAmount>5.0</spiritAmount>
            <transparency>2</transparency>
            <filtration>filtred</filtration>
            <nutritiveValue>1200</nutritiveValue>
            <bottling>2.5 metal</bottling>
        </chars>
    </beer>
    <beer id="beer2">
        <name>Beloe zoloto</name>
        <type>alive</type>
        <alchoholType>alchohol</alchoholType>
        <manufactor>Alivaria</manufactor>
        <ingridients>
            <water>68</water>
            <malt>11</malt>
            <Hop>14</Hop>
            <sugar>7</sugar>
        </ingridients>
        <chars>
            <spiritAmount>3.8</spiritAmount>
            <transparency>3</transparency>
            <filtration>nonfiltred</filtration>
            <nutritiveValue>1320</nutritiveValue>
            <bottling>0.9 plastic</bottling>
        </chars>
    </beer>
    <beer id="beer3">
        <name>Baltica 0</name>
        <type>ale</type>
        <alchoholType>nonalchohol</alchoholType>
        <manufactor>Baltica</manufactor>
        <ingridients>
            <water>70</water>
            <malt>9</malt>
            <Hop>13</Hop>
            <sugar>8</sugar>
        </ingridients>
        <chars>
            <spiritAmount>0</spiritAmount>
            <transparency>1</transparency>
            <filtration>filtred</filtration>
            <nutritiveValue>1600</nutritiveValue>
            <bottling>0.5 glass</bottling>
        </chars>
    </beer>
</beers>
